// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const insertLog = `-- name: InsertLog :one
INSERT INTO logs (source, level, message, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, source, level, message, metadata, created_at
`

type InsertLogParams struct {
	Source   string `json:"source"`
	Level    string `json:"level"`
	Message  string `json:"message"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, insertLog, arg.Source, arg.Level, arg.Message, arg.Metadata)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Level,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, source, level, message, metadata, created_at
FROM logs
WHERE id = $1
`

func (q *Queries) GetLogByID(ctx context.Context, id int64) (Log, error) {
	row := q.db.QueryRow(ctx, getLogByID, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Level,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, source, level, message, metadata, created_at
FROM logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error) {
	rows, err := q.db.Query(ctx, listLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Level,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
