// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID        int64     `json:"id"`
	Source    string    `json:"source"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type Diagnostic struct {
	ID         int64       `json:"id"`
	LogID      int64       `json:"log_id"`
	Summary    string      `json:"summary"`
	Severity   string      `json:"severity"`
	Suggestion pgtype.Text `json:"suggestion"`
	ModelUsed  pgtype.Text `json:"model_used"`
	TokensUsed pgtype.Int4 `json:"tokens_used"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}
